<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title_Search</name>
   <tag></tag>
   <elementGuidId>f228118e-f8f2-43d1-bdac-071403234a65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='select2-drop']//div[@class='select2-search']//input[@class='select2-input'][@role='combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='select2-drop']//div[@class='select2-search']//input[@class='select2-input'][@role='combobox']</value>
   </webElementProperties>
</WebElementEntity>
